# -*- coding: utf-8 -*-

#!/usr/bin/env python

# labelprinter.py
#

# Copyright 2015 Jorge Tornero Nunez http://imasdemase.com
#
# This file is part of Etikreator, V1.0
#
# Etikreator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Etikreator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Etikreator. If not, see <http://www.gnu.org/licenses/>.

# Form implementation generated from reading ui file 'labelprinter.ui'
#
# Created: Mon Jul  6 16:52:03 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_LabelPrinter(object):
    def setupUi(self, LabelPrinter):
        LabelPrinter.setObjectName(_fromUtf8("LabelPrinter"))
        LabelPrinter.resize(250, 220)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LabelPrinter.sizePolicy().hasHeightForWidth())
        LabelPrinter.setSizePolicy(sizePolicy)
        LabelPrinter.setMinimumSize(QtCore.QSize(250, 220))
        LabelPrinter.setMaximumSize(QtCore.QSize(250, 220))
        self.centralwidget = QtGui.QWidget(LabelPrinter)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.lab_tab = QtGui.QWidget()
        self.lab_tab.setObjectName(_fromUtf8("lab_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.lab_tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.lab_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lab_species_combo = QtGui.QComboBox(self.lab_tab)
        self.lab_species_combo.setEditable(True)
        self.lab_species_combo.setObjectName(_fromUtf8("lab_species_combo"))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.lab_species_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.lab_species_combo, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.lab_tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lab_date = QtGui.QDateEdit(self.lab_tab)
        self.lab_date.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_date.setDate(QtCore.QDate(2015, 7, 22))
        self.lab_date.setCalendarPopup(True)
        self.lab_date.setObjectName(_fromUtf8("lab_date"))
        self.gridLayout_2.addWidget(self.lab_date, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.lab_tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.lab_origin_combo = QtGui.QComboBox(self.lab_tab)
        self.lab_origin_combo.setEditable(True)
        self.lab_origin_combo.setObjectName(_fromUtf8("lab_origin_combo"))
        self.lab_origin_combo.addItem(_fromUtf8(""))
        self.lab_origin_combo.addItem(_fromUtf8(""))
        self.lab_origin_combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.lab_origin_combo, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.lab_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.lab_start_spinbox = QtGui.QSpinBox(self.lab_tab)
        self.lab_start_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_start_spinbox.setMinimum(1)
        self.lab_start_spinbox.setMaximum(9999)
        self.lab_start_spinbox.setProperty("value", 1)
        self.lab_start_spinbox.setObjectName(_fromUtf8("lab_start_spinbox"))
        self.gridLayout_2.addWidget(self.lab_start_spinbox, 3, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.lab_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.lab_end_spinbox = QtGui.QSpinBox(self.lab_tab)
        self.lab_end_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_end_spinbox.setMinimum(1)
        self.lab_end_spinbox.setMaximum(9999)
        self.lab_end_spinbox.setProperty("value", 100)
        self.lab_end_spinbox.setObjectName(_fromUtf8("lab_end_spinbox"))
        self.gridLayout_2.addWidget(self.lab_end_spinbox, 4, 1, 1, 1)
        self.print_lab_labels_btn = QtGui.QPushButton(self.lab_tab)
        self.print_lab_labels_btn.setObjectName(_fromUtf8("print_lab_labels_btn"))
        self.gridLayout_2.addWidget(self.print_lab_labels_btn, 5, 0, 1, 2)
        self.tabWidget.addTab(self.lab_tab, _fromUtf8(""))
        self.survey_tab = QtGui.QWidget()
        self.survey_tab.setObjectName(_fromUtf8("survey_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.survey_tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.survey_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.srv_species_combo = QtGui.QComboBox(self.survey_tab)
        self.srv_species_combo.setEditable(True)
        self.srv_species_combo.setObjectName(_fromUtf8("srv_species_combo"))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.srv_species_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.srv_species_combo, 1, 1, 1, 1)
        self.print_srv_labels_btn = QtGui.QPushButton(self.survey_tab)
        self.print_srv_labels_btn.setObjectName(_fromUtf8("print_srv_labels_btn"))
        self.gridLayout_3.addWidget(self.print_srv_labels_btn, 5, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.survey_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.srv_haul_spinbox = QtGui.QSpinBox(self.survey_tab)
        self.srv_haul_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.srv_haul_spinbox.setMinimum(1)
        self.srv_haul_spinbox.setMaximum(999)
        self.srv_haul_spinbox.setProperty("value", 1)
        self.srv_haul_spinbox.setObjectName(_fromUtf8("srv_haul_spinbox"))
        self.gridLayout_3.addWidget(self.srv_haul_spinbox, 2, 1, 1, 1)
        self.srv_survey_combo = QtGui.QComboBox(self.survey_tab)
        self.srv_survey_combo.setEditable(True)
        self.srv_survey_combo.setObjectName(_fromUtf8("srv_survey_combo"))
        self.srv_survey_combo.addItem(_fromUtf8(""))
        self.srv_survey_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.srv_survey_combo, 0, 1, 1, 1)
        self.srv_end_spinbox = QtGui.QSpinBox(self.survey_tab)
        self.srv_end_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.srv_end_spinbox.setMinimum(1)
        self.srv_end_spinbox.setMaximum(9999)
        self.srv_end_spinbox.setProperty("value", 50)
        self.srv_end_spinbox.setObjectName(_fromUtf8("srv_end_spinbox"))
        self.gridLayout_3.addWidget(self.srv_end_spinbox, 4, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.survey_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.survey_tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.survey_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.srv_start_spinbox = QtGui.QSpinBox(self.survey_tab)
        self.srv_start_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.srv_start_spinbox.setMinimum(1)
        self.srv_start_spinbox.setMaximum(9999)
        self.srv_start_spinbox.setProperty("value", 1)
        self.srv_start_spinbox.setObjectName(_fromUtf8("srv_start_spinbox"))
        self.gridLayout_3.addWidget(self.srv_start_spinbox, 3, 1, 1, 1)
        self.tabWidget.addTab(self.survey_tab, _fromUtf8(""))
        self.printer_tab = QtGui.QWidget()
        self.printer_tab.setObjectName(_fromUtf8("printer_tab"))
        self.layoutWidget = QtGui.QWidget(self.printer_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 186, 42))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.printer_ip = QtGui.QLineEdit(self.layoutWidget)
        self.printer_ip.setAlignment(QtCore.Qt.AlignCenter)
        self.printer_ip.setObjectName(_fromUtf8("printer_ip"))
        self.gridLayout.addWidget(self.printer_ip, 1, 0, 1, 1)
        self.printer_port = QtGui.QSpinBox(self.layoutWidget)
        self.printer_port.setAlignment(QtCore.Qt.AlignCenter)
        self.printer_port.setMaximum(65535)
        self.printer_port.setProperty("value", 9100)
        self.printer_port.setObjectName(_fromUtf8("printer_port"))
        self.gridLayout.addWidget(self.printer_port, 1, 1, 1, 1)
        self.tabWidget.addTab(self.printer_tab, _fromUtf8(""))
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        LabelPrinter.setCentralWidget(self.centralwidget)

        self.retranslateUi(LabelPrinter)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LabelPrinter)

    def retranslateUi(self, LabelPrinter):
        LabelPrinter.setWindowTitle(QtGui.QApplication.translate("LabelPrinter", "ETIKATOR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LabelPrinter", "Especie", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(0, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(1, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(2, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(3, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus (G)", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(4, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_species_combo.setItemText(5, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus (G)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("LabelPrinter", "Fecha", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_date.setDisplayFormat(QtGui.QApplication.translate("LabelPrinter", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("LabelPrinter", "Origen", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_origin_combo.setItemText(0, QtGui.QApplication.translate("LabelPrinter", "Lonja de Cádiz", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_origin_combo.setItemText(1, QtGui.QApplication.translate("LabelPrinter", "Lonja de Sanlúcar", None, QtGui.QApplication.UnicodeUTF8))
        self.lab_origin_combo.setItemText(2, QtGui.QApplication.translate("LabelPrinter", "Lonja de Barbate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("LabelPrinter", "Núm. Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("LabelPrinter", "Núm. Final", None, QtGui.QApplication.UnicodeUTF8))
        self.print_lab_labels_btn.setText(QtGui.QApplication.translate("LabelPrinter", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.lab_tab), QtGui.QApplication.translate("LabelPrinter", "Lonja", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("LabelPrinter", "Núm. Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(0, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(1, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(2, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(3, QtGui.QApplication.translate("LabelPrinter", "E. encrasicolus (G)", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(4, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus (P)", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_species_combo.setItemText(5, QtGui.QApplication.translate("LabelPrinter", "S. pilchardus (G)", None, QtGui.QApplication.UnicodeUTF8))
        self.print_srv_labels_btn.setText(QtGui.QApplication.translate("LabelPrinter", "Imprimir", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("LabelPrinter", "Campaña", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_survey_combo.setItemText(0, QtGui.QApplication.translate("LabelPrinter", "ECOCADIZ-201507", None, QtGui.QApplication.UnicodeUTF8))
        self.srv_survey_combo.setItemText(1, QtGui.QApplication.translate("LabelPrinter", "ECOCADIZ-R-2015", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("LabelPrinter", "Pesca", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("LabelPrinter", "Especie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("LabelPrinter", "Núm. Final", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.survey_tab), QtGui.QApplication.translate("LabelPrinter", "Campaña", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LabelPrinter", "<center>Printer IP</center>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LabelPrinter", "<center>Port</center>", None, QtGui.QApplication.UnicodeUTF8))
        self.printer_ip.setText(QtGui.QApplication.translate("LabelPrinter", "192.168.2.6", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.printer_tab), QtGui.QApplication.translate("LabelPrinter", "Impresora", None, QtGui.QApplication.UnicodeUTF8))

